<?php

/**
 * LORUM IPSUM GENERATOR
 * 
 * @name        lipsum
 * @package     library 
 * @version     
 * @since       08-Oct-2019 11:27:57
 * @author      jonthompson
 * @abstract    
 */


namespace jthompson\tools\strings;

class lipsum {
    const text = [
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sed ligula vel orci blandit laoreet. Interdum et malesuada fames ac ante ipsum primis in faucibus. Quisque eros ligula, pulvinar iaculis leo et, tempor tempus odio. Etiam facilisis malesuada turpis, ac lobortis justo ornare ac. Vestibulum eget turpis arcu. Cras vel ultricies diam, et tempor magna. Vestibulum nec tortor at quam fringilla facilisis. Sed tempus quam ut dui sollicitudin congue. Nunc dui dolor, tincidunt vel tortor id, convallis tincidunt neque. Aenean sed dapibus diam, ut lacinia ante. Pellentesque bibendum nisl auctor dapibus dignissim. Nulla vestibulum velit ex, eget viverra justo pretium quis. Duis mi neque, malesuada nec nulla vel, ultricies ornare enim. Proin nec dictum mauris, ac cursus augue.",
        "Morbi vel odio vulputate, bibendum felis pulvinar, ultrices lacus. In nulla felis, faucibus et aliquet ac, dictum ut augue. Fusce ante magna, aliquam quis velit nec, commodo dictum leo. Nullam in ante placerat, tempus sapien nec, euismod sem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam tempor posuere lacus. Etiam aliquam, felis ac tempus laoreet, erat purus finibus sapien, eu imperdiet risus nisi id lectus. Nam condimentum fringilla pretium. Duis malesuada tortor nibh, et consectetur erat ultricies a. Donec orci turpis, convallis a lacus eget, consequat sollicitudin nibh. Integer vitae condimentum metus, vel euismod arcu. Mauris facilisis tempor vehicula. Praesent tristique dolor vel ipsum malesuada, vel ultricies eros efficitur.",
        "Vestibulum eget sagittis ante, quis egestas est. Aliquam vel leo sit amet nulla porttitor lobortis. Praesent nec urna convallis, tristique ante quis, molestie neque. Mauris ornare ullamcorper eros, vitae convallis sem rhoncus et. Suspendisse eget eros vel metus scelerisque tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus. Vivamus convallis maximus semper. Aliquam auctor mi nisi, at pellentesque justo lacinia ut. Sed urna sem, volutpat quis molestie et, cursus non libero.",
        "Praesent faucibus luctus libero id luctus. Donec porta fringilla eros eget faucibus. Ut eu augue nisi. Suspendisse porta felis id purus fringilla, id interdum nunc tincidunt. Vestibulum pharetra imperdiet magna commodo fermentum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Curabitur ut felis orci. Integer tempus consequat vulputate. Nam mattis neque at scelerisque luctus.",
        "Ut ut gravida nunc. Sed sit amet tortor felis. Vivamus vulputate nibh nisl, at facilisis tellus egestas eu. In pretium aliquam porta. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque ornare tincidunt orci blandit consectetur. Aliquam lobortis ultrices nibh, vitae luctus purus ullamcorper vitae. Aenean efficitur, sem ac dictum tincidunt, velit orci tristique erat, efficitur consequat tortor sapien vitae dui. Nullam rutrum ex sit amet ex varius pellentesque.",
        "Proin velit eros, fringilla ut euismod id, lacinia luctus purus. Donec at urna at odio iaculis tincidunt suscipit non neque. Cras ac aliquet ante, non tristique sapien. Nulla convallis eget purus eget tincidunt. In hac habitasse platea dictumst. Mauris porttitor nec nisi sed fringilla. Nam tincidunt mi et semper consectetur. Nam quis pulvinar ante, a tincidunt elit. Quisque lacinia suscipit purus, id dignissim nunc mattis vel. Maecenas pharetra convallis nisl, ac finibus nibh auctor at. Praesent fringilla, nisl at convallis consequat, nisi sapien commodo eros, sit amet commodo libero neque finibus arcu. Nunc nec sapien id mi commodo posuere. Nulla lectus elit, molestie at sapien sed, vestibulum sollicitudin erat.",
        "Etiam urna nibh, vehicula eget eros non, porta hendrerit elit. Nam sed tincidunt turpis, at pharetra leo. Ut vitae iaculis nunc. Quisque varius rutrum nisi eget cursus. Duis at dignissim mauris. Proin ullamcorper ullamcorper lacinia. Maecenas metus dui, fermentum porta nibh a, fermentum ullamcorper lorem.",
        "Proin ac orci pharetra nisl vehicula eleifend in vitae sapien. Vivamus nisl mauris, maximus non diam at, fermentum dapibus justo. Sed dictum lorem viverra faucibus rutrum. Morbi semper accumsan turpis, quis laoreet lacus pellentesque non. Donec tristique eget dolor eu efficitur. Nunc aliquam nunc et elit auctor, sit amet porttitor odio vehicula. In urna elit, congue at varius maximus, tincidunt sed ligula. Curabitur sit amet molestie leo. Nulla sit amet dapibus metus. Etiam pretium ornare mauris, non hendrerit enim fringilla sed. Donec ac magna a dui ultrices dignissim et eu felis. Proin sapien massa, euismod ac justo eget, eleifend molestie elit. Donec egestas interdum suscipit.",
        "Vestibulum vitae pharetra ex. Curabitur tristique lorem sit amet risus gravida sollicitudin. Fusce et metus tortor. Maecenas tortor ligula, vehicula vitae egestas sed, convallis sed leo. Nulla justo neque, commodo in consequat id, sollicitudin sed magna. Sed sed viverra purus, nec tincidunt nisl. Donec scelerisque aliquet ex eu fermentum. Sed sollicitudin, risus in egestas mattis, lorem nisl viverra orci, molestie vulputate sapien augue viverra arcu. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nunc faucibus dignissim leo at commodo.",
        "Sed justo enim, rutrum id laoreet eu, dictum eu est. Sed ante metus, mattis a justo non, aliquet rhoncus odio. Aliquam feugiat odio vitae nibh consequat, vitae volutpat purus pulvinar. Vestibulum eget enim auctor, fermentum mi nec, cursus nulla. Cras auctor iaculis sapien, ut vulputate dui ultrices quis. Aliquam at consequat neque. Mauris porttitor ligula a urna hendrerit, et feugiat urna auctor.",
        "Etiam tincidunt suscipit dignissim. Nam et scelerisque nisl. Nam eu leo at augue pellentesque tempor non ac lacus. Integer sed accumsan augue, at iaculis lorem. Donec eu odio iaculis, sollicitudin nulla id, porta lorem. Phasellus quis condimentum tortor. Proin et bibendum nisl, sed sollicitudin ex. Phasellus commodo porta orci. Cras ut consequat sapien.",
        "In feugiat neque eget interdum dignissim. Mauris volutpat tortor sapien. Integer tempor sapien leo, at fermentum nisi iaculis ac. Aliquam ultricies eros eu malesuada vulputate. Ut ligula est, facilisis sit amet viverra sed, facilisis eget nisi. Nam sollicitudin nec odio vitae molestie. Phasellus dignissim porttitor finibus. Ut pellentesque malesuada felis, non tristique felis interdum quis. Maecenas eget nibh in nisi imperdiet porta. Mauris non sollicitudin neque. Morbi ut tellus tortor. Nulla ipsum libero, pharetra nec turpis a, suscipit commodo sem. Nulla maximus condimentum massa, id pharetra odio volutpat nec. Quisque et laoreet velit.",
        "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nulla convallis massa eu malesuada blandit. Sed ultricies, lacus a imperdiet sodales, ante purus porta arcu, eget ultrices metus eros vitae lectus. Integer tempor ac mauris non lacinia. Donec at odio auctor, sollicitudin nisi vitae, interdum diam. Cras porta convallis lacus at tempus. Maecenas et accumsan mi. Curabitur quis interdum nibh, sit amet elementum urna. Proin lobortis felis sit amet orci euismod aliquam. Aenean dictum a risus nec luctus.",
        "Donec vulputate nibh varius, aliquam lacus a, faucibus sem. Phasellus tempus orci mi, viverra sodales arcu blandit sit amet. Praesent rutrum, ipsum eget posuere cursus, nibh ante aliquet ex, in egestas orci odio non ante. Donec vitae risus sit amet augue imperdiet malesuada vitae ut lectus. Donec et lorem quis justo facilisis tincidunt sed ut erat. Etiam eu vehicula velit. Nunc vitae dui nec erat tristique molestie et sed leo. Donec dictum in ex et suscipit. Donec quis pellentesque elit. Proin eget est porttitor, fringilla turpis ut, bibendum orci. Ut congue mauris sem, eget sagittis sapien consequat vel. Donec maximus, nisi ut elementum dictum, velit metus laoreet nisi, in dignissim quam purus nec magna. Nullam consectetur gravida magna, ut aliquet purus accumsan sed. Suspendisse accumsan lorem pretium nibh vulputate consectetur. Donec pretium, libero sit amet tempor malesuada, dui sapien pharetra nisl, malesuada elementum justo ex non diam.",
        "Sed ornare porta nulla, vitae fermentum quam commodo nec. Aenean venenatis sit amet tortor quis faucibus. Etiam elit ipsum, viverra vitae interdum quis, lobortis ac purus. Vivamus efficitur ullamcorper posuere. Nam cursus nunc quis sem cursus, in ullamcorper massa blandit. Aenean lacinia placerat urna in consectetur. Integer ut interdum nisi, id auctor purus. Sed rhoncus justo nec arcu interdum, non ultricies dolor euismod. Sed elementum porttitor turpis, non imperdiet enim accumsan ultrices. Curabitur et porta velit, at elementum velit. Sed egestas eros vitae ultrices laoreet. Praesent fermentum commodo urna rutrum vestibulum. Nulla et urna erat. Sed porta libero vitae laoreet pellentesque. Cras blandit, ipsum sit amet ornare lacinia, sapien tortor finibus massa, a euismod dui sapien sed lorem.",
        "Donec consectetur ipsum eget dolor vulputate porta at et eros. Vestibulum feugiat, arcu rutrum tempor viverra, augue quam faucibus metus, nec hendrerit sem lorem ac odio. Donec maximus porta augue, imperdiet iaculis sapien fringilla eu. Suspendisse sed lacinia sem. Phasellus cursus ultricies justo ut dignissim. Ut vel pulvinar nibh. Pellentesque finibus vehicula diam, nec semper nibh viverra non. Pellentesque aliquet metus in ex blandit, vel tincidunt lectus facilisis.",
        "Pellentesque ut dolor ut ante facilisis vehicula nec ut turpis. Phasellus vulputate nunc at lacus accumsan, eget mattis dolor vehicula. Vivamus rutrum cursus tristique. Maecenas mollis laoreet nunc a laoreet. Integer et blandit libero. Duis ex eros, mollis sed mauris quis, tristique aliquet erat. Cras at mauris id lectus condimentum semper nec porta risus. Sed blandit erat posuere diam rhoncus tincidunt. Nam eget vehicula ipsum.",
        "Suspendisse potenti. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Nunc ultrices tristique ipsum ac porta. Nulla scelerisque lacus sit amet urna tristique dictum. Maecenas fringilla odio orci, eget ultrices sapien placerat eu. Etiam dolor felis, placerat convallis purus sed, sodales tincidunt felis. Mauris placerat, nibh at lobortis consequat, lacus lorem condimentum justo, non iaculis mauris dolor vitae orci. Vestibulum lobortis nulla tincidunt diam aliquam convallis. Sed augue neque, posuere et pharetra ultricies, cursus a turpis. Morbi quis quam dapibus, dictum elit eget, ultrices ligula.",
        "Sed erat sem, iaculis tincidunt eros in, porttitor dictum nulla. Mauris malesuada enim a sem viverra dictum. Morbi fringilla ornare ornare. Fusce nec facilisis felis. Phasellus fermentum erat sed lorem feugiat porttitor. Mauris finibus bibendum nisi ac ultrices. Duis varius dolor eros, eu fermentum nibh auctor eget. Mauris in dui eget metus tincidunt consectetur. Donec feugiat porta est vitae scelerisque. Quisque consectetur elit vitae lacus iaculis sagittis. In finibus elit non turpis rutrum tincidunt. Nulla interdum pulvinar libero, non varius arcu malesuada ut.",
        "Praesent metus urna, feugiat sed eleifend at, condimentum a sem. Nam hendrerit nulla pellentesque, lobortis felis vitae, pretium odio. Quisque mi arcu, faucibus id venenatis eget, pretium id lacus. Cras ornare tempus tellus, id sodales ipsum. Nullam in mattis velit. Nam at est orci. Donec malesuada arcu non risus porttitor, vitae sodales metus dapibus. Cras mauris diam, ultrices id nibh sit amet, vulputate posuere diam. Sed non quam sit amet dolor eleifend malesuada. Aliquam lobortis feugiat gravida. Sed malesuada faucibus quam eget pellentesque. In ut dolor quis mauris porta aliquet. Morbi ultrices sem eu turpis ornare fermentum. Nulla efficitur dapibus ex eget vulputate. Nam gravida justo sit amet est maximus, a lobortis metus efficitur. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.",
        "Aliquam id dictum ex, vel ullamcorper justo. Curabitur elementum venenatis ex sit amet euismod. Pellentesque bibendum magna vitae lectus scelerisque eleifend. Curabitur lectus neque, vehicula ut mi feugiat, placerat congue lorem. Etiam convallis lobortis mi ut convallis. Etiam dignissim sapien vel convallis ullamcorper. Mauris rhoncus in orci sed tempor. In ac ultrices dui. Quisque tincidunt tristique suscipit. Fusce eget rutrum nisi.",
        "Vivamus luctus, odio eget hendrerit bibendum, sapien risus viverra risus, et ullamcorper lacus elit vel enim. Mauris eu porta mauris. Duis ac odio euismod, fringilla ipsum tincidunt, molestie nisl. In ut dignissim nisi. Suspendisse sed elementum libero. Nullam venenatis, tellus eget hendrerit condimentum, mi massa luctus sem, ac placerat odio nulla id odio. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In eget risus sapien. Maecenas posuere, eros ac varius condimentum, massa dui convallis ex, sit amet euismod eros augue non massa. Donec dictum vehicula ornare. Praesent nec sodales ex, eget condimentum diam. Nam quis magna semper, efficitur nibh sit amet, ultrices urna. Cras posuere orci tempor blandit tristique.",
        "Vestibulum fermentum lectus id mauris sodales porttitor non a ex. Ut in mattis ex. Nulla a elementum erat. In quis tempus justo. Proin non semper purus. Nam orci erat, elementum ut ultricies vitae, ullamcorper vitae risus. Curabitur sit amet libero mi. Curabitur eu nisi at dui lacinia scelerisque. Nulla dapibus ornare est sit amet fringilla. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque enim metus, elementum sit amet tempor sed, sagittis luctus velit. Nunc congue orci nunc, et viverra nisi gravida nec. Mauris viverra, mauris ut tincidunt aliquam, est odio tempor lectus, eget dapibus nunc eros non purus. Vivamus viverra, nunc sit amet vehicula rhoncus, est lacus consequat massa, sed vehicula neque dolor a turpis. Ut arcu ipsum, rhoncus quis dui at, sodales dapibus risus.",
        "Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum ipsum orci, placerat quis fringilla ut, sagittis ut tortor. Proin facilisis enim vitae gravida consequat. Nam sit amet euismod erat. Vivamus facilisis quam sed ligula sollicitudin interdum. Donec consequat quam tortor, imperdiet ultrices nisi eleifend ut. Nam non ornare neque. Phasellus congue velit ante, a viverra nisl congue a. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In ultrices nulla sed eros vehicula fringilla. Morbi nunc sapien, malesuada ac urna nec, lobortis auctor massa. Ut iaculis porttitor mollis. Donec consequat fermentum justo, at mollis nisl elementum ac. Suspendisse eget bibendum risus. Sed nec iaculis enim.",
        "Mauris ut aliquet odio. In hac habitasse platea dictumst. Duis in ante nec justo fringilla volutpat. Etiam mollis lacus quis tellus mattis, venenatis pellentesque nisl consectetur. Aliquam nisl urna, vulputate ac iaculis eu, tempor sit amet justo. Nunc fermentum ullamcorper dapibus. Nullam eget volutpat lorem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Proin condimentum sit amet quam ut porttitor. Sed velit est, maximus quis urna ut, pretium dignissim risus. Vestibulum risus augue, fermentum sit amet nibh vel, maximus viverra enim. In a aliquam odio. Proin non mauris vel nunc porta pellentesque.",
        "Nulla et dapibus neque. Pellentesque dolor libero, ultrices eu dictum facilisis, aliquam quis metus. Etiam dolor justo, imperdiet non rhoncus a, eleifend sit amet ex. Donec ante nulla, volutpat ut mauris at, sodales dapibus eros. Donec et lobortis ligula. Nullam non iaculis nulla. Donec varius sit amet mi pharetra laoreet. Morbi in urna porttitor, consequat nisl in, dapibus eros. Phasellus ac augue velit. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus scelerisque eleifend pulvinar.",
        "Vivamus egestas odio nisl, sed imperdiet nibh placerat a. Sed et varius tellus. Nam a tincidunt magna. Cras facilisis eget ante nec aliquam. Maecenas hendrerit sem nisl, nec accumsan nibh dignissim sit amet. Fusce pharetra accumsan tortor, sed tempor libero scelerisque et. Donec nec hendrerit magna. Aenean semper purus eros, vel semper augue accumsan et. Donec et est vitae sem molestie imperdiet. Sed sed tellus justo. Vivamus eget metus fringilla, suscipit turpis at, malesuada mi. Vestibulum congue augue elit, accumsan ultricies orci suscipit et. Fusce et iaculis leo.",
        "Nam vulputate eleifend accumsan. Sed quam nunc, suscipit porta ultricies sed, viverra nec sem. Donec dignissim condimentum lacus, vitae aliquam risus ornare at. Sed dapibus nibh eget consectetur imperdiet. In maximus bibendum odio. Aliquam vitae turpis odio. Maecenas in diam pharetra, auctor diam ut, porta felis. Duis laoreet risus id justo viverra vestibulum. Nulla at mi malesuada, porttitor arcu eu, lobortis turpis. Proin vitae massa congue, tincidunt justo vitae, eleifend leo. Sed varius tellus non diam vehicula volutpat.",
        "Aliquam scelerisque turpis scelerisque mi ornare tempor. Maecenas eget feugiat elit. Nulla scelerisque commodo euismod. Aliquam ac fringilla diam. Duis at imperdiet felis, ac fringilla ex. Etiam quis feugiat lorem, non suscipit magna. Fusce ultrices lectus eu diam venenatis gravida. Donec sed sagittis est. Cras sodales vulputate dui, nec tempus purus viverra non. Maecenas porta ut odio et faucibus. Vestibulum eleifend erat nunc, et pretium sem placerat at. Duis at lacus sit amet ligula vestibulum molestie. Sed egestas ornare sodales.",
        "Suspendisse lobortis libero at tincidunt ultricies. Nunc luctus tellus in ante scelerisque, non tristique metus viverra. Sed finibus tempus ante ut euismod. Nulla facilisi. Pellentesque cursus ultrices mi at facilisis. Pellentesque cursus mi non tincidunt posuere. Fusce eget quam ex. Curabitur gravida eu libero sit amet ultricies. Donec tempus tincidunt odio, id sollicitudin arcu ullamcorper vitae.",
    ];
    
    public static function single($asParagraphs = TRUE): string {
        $text = self::text[random_int(0, count(self::text) - 1)];
        
        if($asParagraphs === TRUE) {
            $text = "<p>{$text}</p>";
        }
        
        return (string) $text;
    }
    
    public static function show(int $lines = 1, bool $asParagraphs = TRUE): array {
        $return = [];
        
        for($ct = 0; $ct < $lines; $ct++) {
            $text = self::text[random_int(0, count(self::text) - 1)];
            
            if($asParagraphs === TRUE) {
                $text = "<p>{$text}</p>";
            }
            
            $return[] = $text;
        }
        
        return (array) $return;
    }
}